export const CLOTHING_TABS = [
  "Dresses",
  "Tops",
  "Knitwear",
  "Skirts",
  "Trousers",
  "Jackets",
  "Denim",
] as const;

export type ClothingTab = (typeof CLOTHING_TABS)[number];

export type LandingClothingProduct = {
  id: string;
  category: ClothingTab;
  name: string;
  brand: string;
  price: number;
  currency: string;
  imageUrl: string;
  badge?: "New Season" | "Featured";
};

export const LANDING_CLOTHING_PRODUCTS: LandingClothingProduct[] = [
  {
    id: "6upmcbj",
    category: "Dresses",
    brand: "Tiger Mist",
    name: "Janine Mini Dress",
    price: 85,
    currency: "USD",
    imageUrl: "/landing/clothing/6upmcbj.jpg",
    badge: "Featured",
  },
  {
    id: "lg9gttm",
    category: "Dresses",
    brand: "Jaded London",
    name: "One Shoulder Graphic Dress",
    price: 95,
    currency: "USD",
    imageUrl: "/landing/clothing/lg9gttm.jpg",
  },
  {
    id: "wwtjp0h",
    category: "Dresses",
    brand: "GUIZIO",
    name: "Cowl Slip Mini Dress",
    price: 288,
    currency: "USD",
    imageUrl: "/landing/clothing/wwtjp0h.jpg",
    badge: "New Season",
  },
  {
    id: "pkppsbm",
    category: "Dresses",
    brand: "AGOLDE",
    name: "Abbi Dress",
    price: 150,
    currency: "USD",
    imageUrl: "/landing/clothing/pkppsbm.jpg",
  },
  {
    id: "jacxfgk",
    category: "Tops",
    brand: "AGOLDE",
    name: "Ester Twist Tank",
    price: 178,
    currency: "USD",
    imageUrl: "/landing/clothing/jacxfgk.jpg",
    badge: "Featured",
  },
  {
    id: "drij0um",
    category: "Tops",
    brand: "Citizens of Humanity",
    name: "Isabel Rib Tank Top",
    price: 98,
    currency: "USD",
    imageUrl: "/landing/clothing/drij0um.jpg",
  },
  {
    id: "tmk1cr6",
    category: "Tops",
    brand: "GRLFRND",
    name: "Muscle Tank",
    price: 59,
    currency: "USD",
    imageUrl: "/landing/clothing/tmk1cr6.jpg",
    badge: "New Season",
  },
  {
    id: "l8rmr2e",
    category: "Tops",
    brand: "EAVES",
    name: "Sinai Top",
    price: 189,
    currency: "USD",
    imageUrl: "/landing/clothing/l8rmr2e.jpg",
  },
  {
    id: "6eragnx",
    category: "Knitwear",
    brand: "Cult Gaia",
    name: "Hartley Knit Dress",
    price: 598,
    currency: "USD",
    imageUrl: "/landing/clothing/6eragnx.jpg",
    badge: "Featured",
  },
  {
    id: "4lgw6k9",
    category: "Knitwear",
    brand: "Balmain",
    name: "Cotton Blend Knit Top",
    price: 693,
    currency: "USD",
    imageUrl: "/landing/clothing/4lgw6k9.jpg",
  },
  {
    id: "541wmas",
    category: "Knitwear",
    brand: "EAVES",
    name: "Susen Rib Knit V-neck Top",
    price: 159,
    currency: "USD",
    imageUrl: "/landing/clothing/541wmas.jpg",
    badge: "New Season",
  },
  {
    id: "brg8ifd",
    category: "Knitwear",
    brand: "SRG",
    name: "Sidonia Top",
    price: 250,
    currency: "USD",
    imageUrl: "/landing/clothing/brg8ifd.jpg",
  },
  {
    id: "wughwcm",
    category: "Skirts",
    brand: "Bardot",
    name: "Lorenzo Denim Mini Skirt",
    price: 104,
    currency: "USD",
    imageUrl: "/landing/clothing/wughwcm.jpg",
    badge: "Featured",
  },
  {
    id: "nux2153",
    category: "Skirts",
    brand: "AGOLDE",
    name: "Keira Mini Skirt",
    price: 135,
    currency: "USD",
    imageUrl: "/landing/clothing/nux2153.jpg",
  },
  {
    id: "m8ucdar",
    category: "Skirts",
    brand: "GRLFRND",
    name: "Amber Skirt",
    price: 95,
    currency: "USD",
    imageUrl: "/landing/clothing/m8ucdar.jpg",
    badge: "New Season",
  },
  {
    id: "fzxx5ss",
    category: "Trousers",
    brand: "AGOLDE",
    name: "Recycled Leather Pant",
    price: 112,
    currency: "USD",
    imageUrl: "/landing/clothing/fzxx5ss.jpg",
    badge: "Featured",
  },
  {
    id: "9rbtjom",
    category: "Trousers",
    brand: "Citizens of Humanity",
    name: "Sadie Pull On Pant",
    price: 116,
    currency: "USD",
    imageUrl: "/landing/clothing/9rbtjom.jpg",
  },
  {
    id: "wku2hz0",
    category: "Trousers",
    brand: "GRLFRND",
    name: "Power Hi Waist Cigarette Pant",
    price: 192,
    currency: "USD",
    imageUrl: "/landing/clothing/wku2hz0.jpg",
    badge: "New Season",
  },
  {
    id: "iarlx2p",
    category: "Jackets",
    brand: "AGOLDE",
    name: "Edie Leather Puffer",
    price: 476,
    currency: "USD",
    imageUrl: "/landing/clothing/iarlx2p.jpg",
    badge: "Featured",
  },
  {
    id: "djdydgh",
    category: "Jackets",
    brand: "Citizens of Humanity",
    name: "Nadja Jacket",
    price: 144,
    currency: "USD",
    imageUrl: "/landing/clothing/djdydgh.jpg",
    badge: "New Season",
  },
  {
    id: "oeslydo",
    category: "Jackets",
    brand: "GRLFRND",
    name: "Daria Oversized Denim Jacket",
    price: 130,
    currency: "USD",
    imageUrl: "/landing/clothing/oeslydo.jpg",
  },
  {
    id: "tquwu3l",
    category: "Jackets",
    brand: "AGOLDE",
    name: "Iona Skye Jacket",
    price: 346,
    currency: "USD",
    imageUrl: "/landing/clothing/tquwu3l.jpg",
  },
  {
    id: "du6tehv",
    category: "Denim",
    brand: "AGOLDE",
    name: "Low Curve Wide Leg Jean",
    price: 248,
    currency: "USD",
    imageUrl: "/landing/clothing/du6tehv.jpg",
    badge: "Featured",
  },
  {
    id: "td7y7re",
    category: "Denim",
    brand: "AGOLDE",
    name: "Vana Jean",
    price: 262,
    currency: "USD",
    imageUrl: "/landing/clothing/td7y7re.jpg",
  },
  {
    id: "duv0xgc",
    category: "Denim",
    brand: "Levi's",
    name: "Ribcage Full Length Straight",
    price: 83,
    currency: "USD",
    imageUrl: "/landing/clothing/duv0xgc.jpg",
    badge: "New Season",
  },
  {
    id: "kzq7p4f",
    category: "Denim",
    brand: "AGOLDE",
    name: "90s Pinch Waist Long Jean",
    price: 124,
    currency: "USD",
    imageUrl: "/landing/clothing/kzq7p4f.jpg",
  },
];

export function productsForTab(tab: ClothingTab): LandingClothingProduct[] {
  return LANDING_CLOTHING_PRODUCTS.filter((p) => p.category === tab);
}

export const LANDING_CLOTHING_PRELOAD = productsForTab("Dresses").map(
  (p) => p.imageUrl,
);
